# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerManager', '0002_containers_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='containers',
            name='restartPolicy',
            field=models.CharField(default='no', max_length=8),
        ),
    ]
