# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dockerManager', '0004_containers_startonreboot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containers',
            name='restartPolicy',
        ),
    ]
