# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerManager', '0007_auto_20181220_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='containers',
            name='env',
            field=models.TextField(default='{}'),
        ),
    ]
